config/routes.rb
BellaLuna::Application.routes.draw do
 
  resources :menus

  root :to => 'pages#home'
 
  #get "pages/home"
  match '/about',   :to => 'pages#about'
  match '/location',:to => 'pages#location'
  #match '/menu',    :to => 'pages#menu'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  @client = Twitter.user("rezaparang").location
  
  
  private
  
    def client
      Twitter.configure do |config|
        config.consumer_key = 'JQPj7ZQzI53Zsdf079k1fw'
        config.consumer_secret = 'RDove9MoZkZ4BUbmhE9N2sprkibkYlL3fnjtjRBt8'
        config.oauth_token = '16831800-YnnweZQ9OAfU2s8wsW09DAiVsp3j5kZlATtQADw'
        config.oauth_token_secret = 'YcBwYWfgOHAT6Dto8iD5JCLkIjjsbH1aMfWCw'
      end
      #@client ||= Twitter::Client.new
      @client = Twitter.user("rezaparang").location
    end
  
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
    @category_antipasti = Menu.where(:category => 'Antipasti')
    @category_insalate = Menu.where(:category => 'Insalate e Zuppe')
    @category_panini = Menu.where(:category => 'Panini e Foccacia')
    @category_primi = Menu.where(:category => 'Primi')
    @category_secundi = Menu.where(:category => 'Secundi')
    @category_beverages = Menu.where(:category => 'Beverages')
    @category_dolci = Menu.where(:category => 'Dolci')
    @category_cocktails = Menu.where(:category => 'Cocktails')
    #@twitter_timeline = Twitter.user_timeline("bellalunaknox").first.text

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    twitter_user = "bellalunaknox"
    
    @title = "Home"
    
    #begin
    #  @twitter_timeline = Twitter.user_timeline(twitter_user)
    #rescue
    #end
    #make a rescue!
  end
  
  def menus
    @title = "Menu"
  end
  
  def location
    @title = "Location"
  end
  
  def about
    @title = "About"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>Copyright © 2012 Bella Luna - simple. modern. italian.<p>
</div>

app/views/layouts/_header.html.erb
<header>
	<% logo = image_tag("bella_logo.png", :alt => "Bella Luna Restaurant", :class => "logo") %>
	<% yelp = image_tag("yelp.png", :alt => "Find us on Yelp", :class => "social") %>
	<% facebook = image_tag("facebook.png", :alt => "Find us on Facebook", :class => "social") %>
	<% twitter = image_tag("twitter.png", :alt => "Find us on Twitter", :class => "social") %>
	
	<%= link_to logo, root_path %>
	
	<div class="find-us-on-label">Find us on</div>
	<div class="find-us-on">
		<%= link_to yelp, "http://www.yelp.com/biz/bella-luna-knoxville", :target => "_blank" %>
		<%= link_to facebook, "http://www.facebook.com/pages/Bella-Luna-Restaurant/112371618847312", :target => "_blank" %>
		<%= link_to twitter, "https://twitter.com/BellaLunaKnox", :target => "_blank" %>
	</div>
	<div class="reservations">RESERVATIONS: <span>(865) 247-7405<span></div>
    <nav class="round">
      <ul>
        <li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Menus", menus_path %></li>
		<li><%= link_to "Location & Hours", location_path %></li>
		<li><%= link_to "About Us", about_path %></li>
      </ul>
    </nav>
	
	<div><%= @client %></div>
	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bella Luna Restaurant - <%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header-container">
	<%= render 'layouts/header' %>
   </div>
  <div class="main-wrapper">
	
  <%= yield %>

  </div>	
    <%= render 'layouts/footer' %>
</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_small %><br />
    <%= f.text_field :price_small %>
  </div>
  <div class="field">
    <%= f.label :price_large %><br />
    <%= f.text_field :price_large %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<div class="body-wrapper">
	<h1>Our Menu</h1>
	<div class="menu-wrapper">
		<% 4.times do |n| %>
			<img src="/assets/menu-<%= n+1 %>.png" />
		<% end %>
		<% 2.times do |n| %>
			<img src="/assets/children-<%= n+1 %>.png" />
		<% end %>
		<% 2.times do |n| %>
			<img src="/assets/lunch-<%= n+1 %>.png" />
		<% end %>
		<% 2.times do |n| %>
			<img src="/assets/brunch-<%= n+1 %>.png" />
		<% end %>
		<% 9.times do |n| %>
			<img src="/assets/drinks-<%= n+1 %>.png" />
		<% end %>
	</div>
</div>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menu.name %>
</p>

<p>
  <b>Category:</b>
  <%= @menu.category %>
</p>

<p>
  <b>Description:</b>
  <%= @menu.description %>
</p>

<p>
  <b>Price small:</b>
  <%= @menu.price_small %>
</p>

<p>
  <b>Price large:</b>
  <%= @menu.price_large %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/pages/about.html.erb
<div class="body-wrapper">

  <h1>About Us</h1>

<!-- <div class="location-right-col">
     </div>
-->
  <div class="about-left-col">
    <p><%= image_tag("JBP-4.png", :alt => "Donna Parang and Christin Love", :class => "about-pic") %><%=raw t("about.text") %></p>
  </div>

  <div style="clear:both"></div>

</div>

app/views/pages/home.html.erb
<script type="text/javascript">
$(document).ready(function() {
    $('.slideshow').cycle({
		fx: 'fade' // choose your transition type, ex: fade, scrollUp, shuffle, etc...
	});
});
</script>

<div class="main-pic-container">
  <div class="slideshow">
  	<%= image_tag("hero_2.png", :alt => "Bruschetta") %>
    <%= image_tag("hero_1.png", :alt => "Bruschetta") %>
    <%= image_tag("hero_4.png", :alt => "Bruschetta") %>
    <%= image_tag("hero_5.png", :alt => "Bruschetta") %>
    <%= image_tag("hero_3.png", :alt => "Bruschetta") %>
  </div>	
</div>
  <div class="inner-wrapper">
    <div class="dine-left">
	  <h1><%= t("home.header_one") %></h1>
	  <h3><%= t("home.subheader_one") %></h3>
	  <p><%=raw t("home.text_one") %></p>
	</div>
    <div class="dine-center">
      <h3><%= t("home.subheader_two") %></h3>
	  <p><%=raw t("home.text_two")%></p>
    </div>
    <div class="dine-right">
	  <h1><%= t("home.header_two") %></h1>
	  <h3><%= t("home.subheader_three") %></h3>
	  <p><%=raw t("home.text_three") %></p>
	</div>
	<div class="section">
	  <h1><%= t("home.header_three") %></h1>
	  <div class="starters">
		<a href="<%= menus_path %>"><%= image_tag("antipasti.png", :alt => "Antipasti") %></a>
	    <h3>Antipasti</h3>
	  </div>
	  <div class="salads">
		<a href="<%= menus_path %>"><%= image_tag("insalate.png", :alt => "Insalate e Zuppe") %></a>
	    <h3>Insalate e Zuppe</h3>
	  </div>
	  <div class="pasta">
		<a href="<%= menus_path %>"><%= image_tag("pasta.png", :alt => "Pastas") %></a>
	    <h3>Pastas</h3>
	  </div>
	  <div class="desserts">
		<a href="<%= menus_path %>"><%= image_tag("specialties.png", :alt => "House Specialties") %></a>
	    <h3>House Specialties</h3>
	  </div>
	  <div class="clear"></div>
	</div>

<!--Twitter stream and press -->

	<div class="section">
	  <div class="location-container">
	    <h2>Location and Hours</h2>
	    <div>
	    	<p><a target="_blank" href="https://maps.google.com/maps?q=15+Market+Square+Knoxville,+TN+37902&amp;hl=en&amp;sll=37.7577,-122.4376&amp;sspn=0.19136,0.273285&amp;hnear=15+Market+Square+SW,+Knoxville,+Knox,+Tennessee+37902&amp;t=m&amp;z=16">15 Market Square<br />Knoxville, TN 37902</a><br />Phone: 865-247-7405<br />Fax: 865-249-7761</p>
			<p>Monday through Sunday: 11am - 10pm</p>
	    	<br />
			<iframe width="400" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=15+Market+Square,+Knoxville,+TN&amp;aq=1&amp;sll=37.0625,-95.677068&amp;sspn=67.840216,135.263672&amp;ie=UTF8&amp;hq=&amp;hnear=15+Market+Square+SW,+Knoxville,+Tennessee+37902&amp;t=m&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
	    </div>
	  </div>
	  <div class="clear"></div>
	</div>

	
	
	
  </div>
</div>

app/views/pages/location.html.erb
<div class="body-wrapper">

  <h1>Location and Hours</h1>

  <div class="location-left-col">
  	<h3>Location</h3>
      <p>15 Market Square<br />Knoxville, TN 37902<br />Phone: 865-247-7405<br />Fax: 865-249-7761</p>
  	<br />
  	<h3>Hours</h3>
    <p>Monday through Sunday: 11am - 10pm</p>
    <br />
    <iframe width="500" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=15+Market+Square,+Knoxville,+TN&amp;aq=1&amp;sll=37.0625,-95.677068&amp;sspn=67.840216,135.263672&amp;ie=UTF8&amp;hq=&amp;hnear=15+Market+Square+SW,+Knoxville,+Tennessee+37902&amp;t=m&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
  </div>
  
</div>